// Importing necessary utilities from Redux Toolkit Query for API integration
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Retrieving the Rapid API key from environment variables
const rapidApiKey = import.meta.env.VITE_RAPID_API_ARTICLE_KEY;

// Creating an API slice using RTK Query's createApi function
export const articleApi = createApi({
  // A unique string identifier for this API slice. This is used internally by RTK Query
  reducerPath: "articleApi",

  // Base query configuration that uses fetchBaseQuery utility from RTK Query
  // to handle the basic fetching logic for this API
  baseQuery: fetchBaseQuery({
    baseUrl: "https://article-extractor-and-summarizer.p.rapidapi.com/",

    // Configuring headers for the API requests
    prepareHeaders: (headers) => {
      // Setting the API key and host for Rapid API authentication
      headers.set("X-RapidAPI-Key", rapidApiKey);
      headers.set(
        "X-RapidAPI-Host",
        "article-extractor-and-summarizer.p.rapidapi.com"
      );

      // Returning the configured headers
      return headers;
    },
  }),

  // Defining API endpoints using the builder pattern
  endpoints: (builder) => ({
    getSummary: builder.query({
      // Define the query logic. This will be the specific API call for this endpoint
      // We're using encodeURIComponent to ensure the URL parameter is correctly formatted
      query: (params) =>
        `summarize?url=${encodeURIComponent(params.articleUrl)}&length=3`,
    }),
  }),
});

// Exporting the custom hook generated by RTK Query for our API endpoint.
// This can be used in components to trigger this specific API call.
export const { useLazyGetSummaryQuery } = articleApi;
